### ISSUE TITLE
可以加一个把文件夹里的书签展示出来的功能吗

### ISSUE THREAD

**Issue by wxy2015** [a90120411/BookmarkPlus#1]
现在好像是只能新增，不能查看、修改书签

**Comment by a90120411** [comment]
感谢你的建议。
你说的功能是需要重写Chrome原生的书签管理器页面，我目前正在开发。
现阶段只能是搭配着原生的书签管理器来使用。

**Comment by a90120411** [comment]
> 现在好像是只能新增，不能查看、修改书签

感谢你的建议。
你说的功能是需要重写Chrome原生的书签管理器页面，我目前正在开发。
现阶段只能是搭配着原生的书签管理器来使用。

**Comment by KnIfER** [comment]
我的已经可以：
![screenshots](https://github.com/a90120411/BookmarkPlus/assets/11593903/cace3a2b-fcff-46c9-b666-39938c53cea5)

https://knifer.github.io/#/content/%E6%97%A0%E9%99%90%E4%B9%A6%E7%AD%BE_devlog
