### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by BsklWssy** [a90120411/BookmarkPlus#7]
就是好像只能搜到文件夹的子文件夹 再下一级就搜不到了 这个可以优化么 可以搜索所有的文件夹么

**Comment by a90120411** [comment]
双击 Shift 键显示当前所选文件夹的子文件夹，但无法后退，因为目前还没有想到比较好的返回上一层文件夹的交互模式。

---

更多操作：

命令：#[文件夹名称] 
说明：显示文件夹的子文件夹,只找1层深度，需要输入完整文件夹名称，不是模糊搜索。

命令：##p
说明：显示所有固定文件夹。

命令： [文件夹名称] > [关键字] 
说明：显示文件夹内含有关键字的子文件夹。

命令：#[父文件夹] ![新文件夹名称]
说明：在父文件夹内新建文件夹。

命令：![新文件夹名称] 
说明：在根目录新建文件夹

双击Shift键会把下拉列表中文件夹名称复制到搜索框。

**Comment by BsklWssy** [comment]
就是我的第三层级的文件夹直接搜不到 我能不能对所有的文件夹 不管多少级都模糊搜索 把包含搜索名字的文件夹都列出来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月13日(周三) 晚上10:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [a90120411/BookmarkPlus] 提个建议 (Issue #7)




 
双击 Shift 键显示当前所选文件夹的子文件夹，但无法后退，因为目前还没有想到比较好的返回上一层文件夹的交互模式。
 
 
更多操作：
 
命令：#[文件夹名称]
 说明：显示文件夹的子文件夹,只找1层深度，需要输入完整文件夹名称，不是模糊搜索。
 
命令：##p
 说明：显示所有固定文件夹。
 
命令： [文件夹名称] &gt; [关键字]
 说明：显示文件夹内含有关键字的子文件夹。
 
命令：#[父文件夹] ![新文件夹名称]
 说明：在父文件夹内新建文件夹。
 
命令：![新文件夹名称]
 说明：在根目录新建文件夹
 
双击Shift键会把下拉列表中文件夹名称复制到搜索框。

**Comment by a90120411** [comment]
可能我没有完全理解你的意图。当前程序默认搜索就是适用于所有文件夹的，不限层级。
